spring.application.name=payment-service

# Server
server.port=${PORT:8080}

server.forward-headers-strategy=framework

app.openapi.title=Payment Service API
app.openapi.description=REST API for managing Payment Information
app.openapi.version=1.0.0

razorpay.key.id=rzp_test_TeyOJ3X0Iu4ohh
razorpay.key.secret=nKIpqdIQigw9JkVl9N3REWg0

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://medicareplus-970647939758.us-central1.run.app}